parameters:
  TargetProjects: 'src/SFA.DAS.Payments.PeriodEnd.AcceptanceTests/SFA.DAS.Payments.PeriodEnd.AcceptanceTests.csproj'

jobs:
- job: AcceptanceBuild
  displayName: Acceptance Build
  pool:
    name: SLD Build pool

  variables:
  - name: SolutionBaseName
    value: SFA.DAS.Payments.PeriodEnd

  steps:
  - template: /azure-pipelines-templates/build/step/gitversion.yml

  - task: UseDotNet@2
    displayName: 'Use .NET 8 SDK'
    inputs:
      packageType: sdk
      version: '8.x'

  - task: DotNetCoreCLI@2
    displayName: 'Dotnet Restore - Acceptance Project'
    inputs:
      command: restore
      projects: ${{ parameters.TargetProjects }}
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  - task: MSBuild@1
  displayName: 'Build - Acceptance Project'
  inputs:
    solution: ${{ parameters.TargetProjects }}
    msbuildArchitecture: x64
    configuration: '$(BuildConfiguration)'
    msbuildArguments: >
      /p:Platform="AnyCPU"
      /p:Version=$(Build.BuildNumber)
      /p:FileVersion=$(Build.BuildNumber)