parameters:
  SolutionBaseName:
  BuildConfiguration:

jobs:
- job: CodeBuild
  pool:
    name: SLD Build pool
  variables:
  - group: BUILD Management Resources
  - name: SolutionBaseName
    value: SFA.DAS.Payments.PeriodEnd
  steps:
  - template: /azure-pipelines-templates/build/step/gitversion.yml


   # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.PeriodEnd.Messages/SFA.DAS.Payments.PeriodEnd.Messages.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.PeriodEnd.Messages/SFA.DAS.Payments.PeriodEnd.Messages.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.PeriodEnd.Messages/SFA.DAS.Payments.PeriodEnd.Messages.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.PeriodEnd.Model/SFA.DAS.Payments.PeriodEnd.Model.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.PeriodEnd.Model/SFA.DAS.Payments.PeriodEnd.Model.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.PeriodEnd.Model/SFA.DAS.Payments.PeriodEnd.Model.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'


  # task: NuGetCommand@2 - src/SFA.DAS.Payments.PeriodEnd.Messages/SFA.DAS.Payments.PeriodEnd.Messages.csproj
  - task: NuGetCommand@2
    displayName: Restore - src/SFA.DAS.Payments.PeriodEnd.Messages/SFA.DAS.Payments.PeriodEnd.Messages.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.PeriodEnd.Messages/SFA.DAS.Payments.PeriodEnd.Messages.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: NuGetCommand@2 - src/SFA.DAS.Payments.PeriodEnd.Model/SFA.DAS.Payments.PeriodEnd.Model.csproj
  - task: NuGetCommand@2
    displayName: Restore - src/SFA.DAS.Payments.PeriodEnd.Model/SFA.DAS.Payments.PeriodEnd.Model.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.PeriodEnd.Model/SFA.DAS.Payments.PeriodEnd.Model.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'



  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.PeriodEnd.Messages/SFA.DAS.Payments.PeriodEnd.Messages.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'
    
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.PeriodEnd.Model/SFA.DAS.Payments.PeriodEnd.Model.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'


  - task: DotNetCoreCLI@2
    displayName: "Publish $(SolutionBaseName)"
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.Payments.PeriodEnd.Messages/SFA.DAS.Payments.PeriodEnd.Messages.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true

  - task: DotNetCoreCLI@2
    displayName: "Publish $(SolutionBaseName)"
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.Payments.PeriodEnd.Model/SFA.DAS.Payments.PeriodEnd.Model.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true


      

  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      Contents: |
        azure/**
      TargetFolder: $(build.artifactstagingdirectory)/publish
      OverWrite: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Build Artifact
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: drop

  - template: /azure-pipelines-templates/build/step/nuget-pack.yml
    parameters:
      DotNetStandardPackagesToPack: |
        src/SFA.DAS.Payments.PeriodEnd.Messages/SFA.DAS.Payments.PeriodEnd.Messages.csproj;
        src/SFA.DAS.Payments.PeriodEnd.Model/SFA.DAS.Payments.PeriodEnd.Model.csproj;