parameters:
  TargetProject: 'src/SFA.DAS.Payments.PeriodEnd.AcceptanceTests/SFA.DAS.Payments.PeriodEnd.AcceptanceTests.csproj'

jobs:
- job: AcceptanceBuild
  displayName: Acceptance Build
  pool:
    name: SLD Build pool

  variables:
  - name: SolutionBaseName
    value: SFA.DAS.Payments.PeriodEnd

  steps:
  - template: /azure-pipelines-templates/build/step/gitversion.yml

  - task: NuGetCommand@2
    displayName: 'NuGet restore - Acceptance project'
    inputs:
      command: restore
      restoreSolution: '${{ parameters.TargetProject }}'
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'
      noCache: true

  - task: MSBuild@1
    displayName: 'Build - Acceptance project'
    inputs:
      solution: '${{ parameters.TargetProject }}'
      msbuildArchitecture: x64
      configuration: '$(BuildConfiguration)'
      msbuildArguments: >
        /p:Platform="$(BuildPlatform)"
        /p:Version=$(Build.BuildNumber)
        /p:FileVersion=$(Build.BuildNumber)

  # Only keep this if you actually want to run acceptance tests in CI
  # - task: VSTest@2
  #   displayName: 'Run Acceptance Tests'
  #   inputs:
  #     testSelector: 'testAssemblies'
  #     testAssemblyVer2: |
  #       **\*AcceptanceTests*.dll
  #       !**\*TestAdapter.dll
  #       !**\obj\**
  #     searchFolder: '$(System.DefaultWorkingDirectory)'